server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.223.133:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234

mybatis:
  type-aliases-package: com.lyr.pojo
  mapper-locations: classpath:mapper/*.xml

