server:
  port: 7001
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:3000/eureka/
  instance:
    instance-id: admin-1
    prefer-ip-address: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
spring:
  application:
    name: service-admin
  redis:
    host: 192.168.223.133
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: -1ms
        min-idle: 10
    timeout: 3000ms
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.223.133:3306/pro?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1000 # 250 30000 获取连接的超时时间
      idle-timeout: 300000 # 10000 600000 空闲时间
      max-lifetime: 600000 # 30000 1800000 最大生存时间，连接在使用时不会生效
      minimum-idle: 10 # 高并发下建议与maximum-pool-size一致
      maximum-pool-size: 25 # 10 连接池大小
      data-source-properties:
        cachePrepStmts: true # 开启sql语句缓存
        prepStmtCacheSize: 250 # 缓存多少条sql语句
        prepStmtCacheSqlLimit: 512 # 缓存sql的最大长度
        useServerPrepStmts: true # 如果可以的话，使用缓存的sql语句
        useLocalSessionState: true # 使用本地配置
        rewriteBatchedStatements: true # 优化update count
        cacheResultSetMetadata: true # 是否缓存ResultSetMetaData
        cacheServerConfiguration: true # 缓存VARIABLES，COLLATION
        elideSetAutoCommits: true # 不进行 set autocommit
        maintainTimeStats: true # 更详细的错误信息，会多2次System.getCurrentTimeMillis()调用
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath*:mapper/**/*.xml