server:
  port: 8081
spring:
  thymeleaf:
    prefix: classpath:/templates/
    encoding: utf-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
    suffix: .html
  datasource:
    password: 1234
    url: jdbc:mysql://192.168.223.133:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
